### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by pawmasz** [qiskit-community/open-science-prize-2021#1]
Hello @ajrazander, I think that link in file `ibmq-qsim-challenge.ipynb` is wrong for "certain optimization problems can be mapped". It points to the same link as in "spin-1/2".

**Comment by ajrazander** [comment]
@pawmasz thank you for bringing this to my attention. The correct link is to a paper: https://arxiv.org/pdf/1712.05771.pdf

I'll update the notebook along with a few other corrected typos shortly.

**Comment by pawmasz** [comment]
Issue fixed in commit a5883aa7d4e77f16e13eed9821fb306ad48c3938. Closing this issue.
