### ISSUE TITLE
ibmq_jakarta

### ISSUE THREAD

**Issue by ZhideLu** [qiskit-community/open-science-prize-2021#2]
When will the ibmq_jakarta quantum computer be open to us to modify our solutions?

**Comment by ajrazander** [comment]
Registrations are processed on an ongoing basis. You can expect access to Jakarta within a few business days of registering :). Keep an eye on your email. In the meantime, you can use a simulator such as
```from qiskit.providers.aer import QasmSimulator```
```backend = QasmSimulator()```

**Comment by RefaatIsmail** [comment]
Hello! I registered on Feb 4th and got an email saying my registration is successful, I’m not sure still how to access IBM Jakarta? The email doesn’t reference any steps I should do and my IBMid account doesn’t have access still

**Comment by ajrazander** [comment]
@RefatIsmail96 message me on the Qiskit slack, and we can get this sorted out
