### ISSUE TITLE
@ operand problem in supplemental materials

### ISSUE THREAD

**Issue by pawmasz** [qiskit-community/open-science-prize-2021#5]
I cannot execute code in supplemental materials:

![image](https://user-images.githubusercontent.com/42217706/147888527-f2698d30-9157-4187-81c4-4321eaf27698.png)

It shows `TypeError: unsupported operand type(s) for @: 'Operator' and 'Operator'`. I cannot find any information in Qiskit documentation on how to solve this.

**Comment by ajrazander** [comment]
@pawmasz what version of python are you running? The @ symbol does matrix multiplication. Since it's not working, feel free to replace the line
`np_ZZ_matrix = CNOT @ I_Rz @ CNOT`
with
`np_ZZ_matrix = np.matmul(np.matmul(CNOT, I_Rz), CNOT)`

**Comment by pawmasz** [comment]
@ajrazander your solution works, thank you.

I'm still wondering how you can multiply two `Operator` (using `*` also doesn't work). I looked over `Operator` code and documentation and don't see operator overloading for `@`. And more strange is that both Python and NumPy should support `@`, and `*` but in my case they don't.

I'm using Python 3.9.7 on Windows 10, but the same behavior is on Linux. This is my environment:
```
Package              Version
-------------------- ---------
argon2-cffi          21.3.0   
argon2-cffi-bindings 21.2.0   
attrs                21.4.0   
backcall             0.2.0    
bleach               4.1.0    
certifi              2021.10.8
cffi                 1.15.0
charset-normalizer   2.0.10
colorama             0.4.4
cryptography         36.0.1
cycler               0.11.0
debugpy              1.5.1
decorator            5.1.0
defusedxml           0.7.1
dill                 0.3.4
entrypoints          0.3
fonttools            4.28.5
idna                 3.3
ipykernel            6.6.1
ipython              7.30.1
ipython-genutils     0.2.0
ipywidgets           7.6.5
jedi                 0.18.1
Jinja2               3.0.3
jsonschema           4.3.3
jupyter-client       7.1.0
jupyter-core         4.9.1
jupyterlab-pygments  0.1.2
jupyterlab-widgets   1.0.2
kiwisolver           1.3.2
MarkupSafe           2.0.1
matplotlib           3.5.1
matplotlib-inline    0.1.3
mistune              0.8.4
mpmath               1.2.1
nbclient             0.5.9
nbconvert            6.4.0
nbformat             5.1.3
nest-asyncio         1.5.4
notebook             6.4.6
ntlm-auth            1.5.0
numpy                1.22.0
packaging            21.3
pandas               1.3.5
pandocfilters        1.5.0
parso                0.8.3
pbr                  5.8.0
pickleshare          0.7.5
Pillow               9.0.0
pip                  21.2.4
ply                  3.11
prometheus-client    0.12.0
prompt-toolkit       3.0.24
psutil               5.9.0
pycparser            2.21
pydot                1.4.2
Pygments             2.11.1
pylatexenc           2.10
pyparsing            3.0.6
pyrsistent           0.18.0
python-constraint    1.4.0
python-dateutil      2.8.2
pytz                 2021.3
pywin32              303
pywinpty             1.1.6
pyzmq                22.3.0
qiskit               0.34.0
qiskit-aer           0.10.1
qiskit-ibmq-provider 0.18.3
qiskit-ignis         0.7.0
qiskit-terra         0.19.1
requests             2.27.0
requests-ntlm        1.1.0
retworkx             0.10.2
scipy                1.7.3
seaborn              0.11.2
Send2Trash           1.8.0
setuptools           58.0.4
six                  1.16.0
stevedore            3.5.0
sympy                1.9
terminado            0.12.1
testpath             0.5.0
tornado              6.1
traitlets            5.1.1
tweedledum           1.1.1
urllib3              1.26.7
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     1.2.3
wheel                0.37.0
widgetsnbextension   3.5.2
wincertstore         0.2
```

**Comment by pawmasz** [comment]
@ajrazander I think I've figured it out.

When using `qiskit.quantum_info.operators.Operator` class, to perform matrix multiplication `A * B` you need to use `B.compose(A)` method because operator `@` is not overloaded in `Operator` class. Possible operations on `Operator` class are described in [documentation](https://qiskit.org/documentation/tutorials/circuits_advanced/02_operators_overview.html).

I've tried this on one of the cells that showed error and comparison between `Qiskit` and `NumPy` gives result `True`:

![image](https://user-images.githubusercontent.com/42217706/148305228-4c434e8f-3b63-4c6a-8bed-49c9114bbdf7.png)

As this causes the notebook to fail regardless of device or Python version, I suggest to change this so others don't face this problem. If you agree I can prepare PR soon.

**Comment by ajrazander** [comment]
Thanks for pointing that out @pawmasz. Here's the specific section in the [docs](https://qiskit.org/documentation/tutorials/circuits_advanced/02_operators_overview.html#Composition) (if you don't want to scroll as much).

**Comment by spacesaba** [comment]
@pawmasz  I am trying to write a product of operators like PA= I^Z^Z and PB=Z^Z^I.... Pproduct= PA*PB.... how i should do in QISKIT ???

**Comment by ajrazander** [comment]
What kind of product are you trying to do? In python, `@` is often overridden to be used for matrix multiplication while `*` is used for element-wise multiplication. If you want to do matrix multiplication between operators used `A.compose(B)`:
```from qiskit.opflow import X, Y, Z, I
pa = I^Z^Z
pb = Z^Z^I
pc = pa.compose(pb)
print(pc)
```
which outputs the expected result `ZIZ`

**Comment by spacesaba** [comment]
How then i should implement it on circuit. Taking  "pa = I^Z" and simultaneously apply it on two qubit like |01>. as i want to make a circuit in which Identity goes to first state|0> and Z apply on |1>

**Comment by spacesaba** [comment]
@ajrazander  thanx for helping
